version: '3.9'

services:

  backend_fr:
    image: wambaborel/mspr-ml-api:latest
    container_name: backend_fr
    ports:
      - "8001:8000"
    environment:
      - COUNTRY=france
    restart: unless-stopped

  backend_us:
    image: wambaborel/mspr-ml-api:latest
    container_name: backend_us
    ports:
      - "8002:8000"
    environment:
      - COUNTRY=usa
    restart: unless-stopped

  backend_ch:
    image: wambaborel/mspr-ml-api:latest
    container_name: backend_ch
    ports:
      - "8003:8000"
    environment:
      - COUNTRY=suisse
    restart: unless-stopped

  etl_db:
    image: wambaborel/mspr-etl-db:latest
    container_name: etl_db
    environment:
      POSTGRES_DB: etldb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    image: wambaborel/mspr-frontend:latest
    container_name: frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - backend_fr
      - backend_us
      - backend_ch

volumes:
  postgres_data:




# Frontend:     http://localhost:3000
# Backend FR:   http://localhost:8001
# Backend US:   http://localhost:8002
# Backend CH:   http://localhost:8003
# ETL DB:       postgresql://user:password@localhost:5432/etldb
